# **TUGAS NUMPY**

---

Nama: Galih Praditya Kurniawan

NIM: 245150201111017

Setelah mengikuti workshop Numpy dan Pandas, tentunya kalian sudah mulai memahami hal-hal apa saja yang akan dilakukan oleh Data Scientist dengan Numpy. Sekarang, saatnya mengukur kemampuan kalian dari apa yang telah kalian dapatkan pada workshop sebelumnya.

**Deadline: Jumat, 21 Februari 2025**


# **📊 Numpy Exercise 📊**

Selamat datang di latihan eksplorasi data menggunakan **Numpy**!  

---

## **📌 Soal 1: Regresi Linear** 📝

Saat offline/online assessment kemarin ada persoalaan **Regresi Linear**, nah coba kamu buat menggunakan python dan numpy termasuk poin-poin berikut: <br>
✅ Fungsi regresi mampu menerima array A dan array B dan memprediksi slope dan intercept<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X <br>

In [58]:
import numpy as np

def linear_regression(arr1, arr2, x):
    
    arr1_mean = np.mean(arr1)
    arr2_mean = np.mean(arr2)

    numerator = np.sum((arr1 - arr1_mean) * (arr2 - arr2_mean))
    denominator = np.sum((arr1 - arr1_mean) ** 2)

    slope = numerator / denominator
    intercept = arr2_mean - slope * arr1_mean

    y = slope * x + intercept

    return y

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 5, 7, 11])
x = 6

y_pred = linear_regression(arr1, arr2, x)
print(f"Nilai y untuk x = {x} adalah: {y_pred}")

Nilai y untuk x = 6 adalah: 12.2


## **📌 Soal 2: Regresi Polinomial** 📝

Saat offline/online assessment kemarin ada persoalan **Regresi Linear**, nah sekarang coba kamu buat **Regresi Polinomial** menggunakan Python dan NumPy, termasuk poin-poin berikut:<br>
✅ Fungsi regresi mampu menerima array A dan array B serta menyesuaikan data dengan polinomial derajat tertentu.<br>
✅ Fungsi regresi mampu memprediksi nilai baru jika diberikan nilai X.<br>
✅ Hasil regresi mencetak koefisien polinomial yang dihasilkan.<br>

In [59]:
def polynomial_regression_predict(arr1, arr2, degree, x):
    
    coefficients = np.polyfit(arr1, arr2, degree)
    
    polynomial = np.poly1d(coefficients)
    
    y = polynomial(x)
    
    return y

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([2, 3, 5, 7, 11])
degree = 2 
x = 6

y_pred = polynomial_regression_predict(arr1, arr2, degree, x)
print(f"Nilai y untuk x = {x} adalah: {y_pred}")

Nilai y untuk x = 6 adalah: 15.200000000000026


## **📌 Soal 3: Random Values Array** 📝

Pertama-tama, buatlah **Array Integer 10x10x10** dengan elemen **random** dan carikan:<br>
1️⃣ Cari elemen minimum dan maksimum dalam array tersebut?<br>
2️⃣ Carilah rata-rata dan median seluruh elemen dalam array tersebut?<br>

In [60]:
arr_random = np.random.rand(10,10, 10)
min = np.min(arr_random)
max = np.max(arr_random)
print("Min:", min)
print("Max:", max)

Min: 0.0005044840333136014
Max: 0.9997591255032953


In [61]:
mean = np.mean(arr_random)
median = np.median(arr_random)
print("Mean:", mean)
print("Median:", median)

Mean: 0.49488304367429337
Median: 0.4984119769701672


## **📌 Soal 4: 2D Array Shenanigans** 📝

Tugas kamu disini adalah membuat **Array 2D** sesuai ketentuan masing-masing soal: <br>
1️⃣ Buatlah **array 10x10** yang memiliki angka "5" sebagai bingkai di seluruh tepi luar dan bagian dalam (selain array) berisi "8"? <br>
2️⃣ Buatlah **array 2d 8x8** dengan pola seperti **checkboard/catur** (1 untuk kotak hitam, 0 untuk kotak putih)?<br>
3️⃣ Buatlah **array 2d 15x15** dengan aturan sebagai berikut:
- Jika suatu angka dapat dibagi 2, isi dengan 2.
- Jika suatu angka dapat dibagi 3, isi dengan 3.
- Jika suatu angka dapat dibagi 5, isi dengan 5.
- Jika suatu angka dapat dibagi oleh lebih dari satu kondisi (misal, 6 bisa dibagi 2 & 3), maka simpan gabungan angka tersebut (misal, 6 → "23", 15 → "35").
- Jika tidak memenuhi kondisi apa pun, isi dengan 0.

In [62]:
arr1 = np.full((10, 10), 8)

arr1[0, :] = 5 
arr1[-1, :] = 5
arr1[:, 0] = 5
arr1[:, -1] = 5

print(arr1)

[[5 5 5 5 5 5 5 5 5 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 8 8 8 8 8 8 8 8 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [63]:
arr2 = np.zeros((8, 8), dtype=int)
arr2[1::2, ::2] = 1
arr2[::2, 1::2] = 1

print(arr2)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [64]:
array = np.zeros((15, 15), dtype=object)

num = 1

for i in range(15):
    for j in range(15):
        result = ""
        
        if num % 2 == 0:
            result += "2"
        if num % 3 == 0:
            result += "3"
        if num % 5 == 0:
            result += "5"
        
        if result == "":
            array[i, j] = 0
        else:
            array[i, j] = result

        num+=1

print(array)

[[0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']
 ['2' 0 '23' 0 '25' '3' '2' 0 '23' '5' '2' '3' '2' 0 '235']
 [0 '2' '3' '2' '5' '23' 0 '2' '3' '25' 0 '23' 0 '2' '35']]


## **📌 Soal 5: Time & Date** 📝

Kamu disini diminta untuk memanfaatkan fitur numpy untuk tanggal: <br>
1️⃣ Bagaimana dengan numpy, kamu bisa mendapatkan tanggal hari ini, kemarin dan esok hari?<br>
2️⃣ Tampilkan hari yang ada di bulan Mei tahun 2020?<br>

In [65]:
today = np.datetime64('today', 'D')
print("Hari ini:", today)

yesterday = today - np.timedelta64(1, 'D')
print("Kemarin:", yesterday)

tomorrow = today + np.timedelta64(1, 'D')
print("Esok hari:", tomorrow)

Hari ini: 2025-02-21
Kemarin: 2025-02-20
Esok hari: 2025-02-22


In [66]:
dates_may_2020 = np.arange('2020-05-01', '2020-06-01', dtype='datetime64[D]')

print("Tanggal di bulan Mei 2020:")
print(dates_may_2020)

Tanggal di bulan Mei 2020:
['2020-05-01' '2020-05-02' '2020-05-03' '2020-05-04' '2020-05-05'
 '2020-05-06' '2020-05-07' '2020-05-08' '2020-05-09' '2020-05-10'
 '2020-05-11' '2020-05-12' '2020-05-13' '2020-05-14' '2020-05-15'
 '2020-05-16' '2020-05-17' '2020-05-18' '2020-05-19' '2020-05-20'
 '2020-05-21' '2020-05-22' '2020-05-23' '2020-05-24' '2020-05-25'
 '2020-05-26' '2020-05-27' '2020-05-28' '2020-05-29' '2020-05-30'
 '2020-05-31']


## **📌 Soal 6: Slicing** 📝

Jika diketahui array `A`, maka buatlah program untuk mendapatkan elemen dibawah ini:
```python
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])
```

1️⃣ Ambil elemen yang berada pada baris `ke-4` dan kolom `ke-2` dari array `A` <br>
2️⃣ Buat `array 2D` yang hanya berisi bilangan prima dari `A` <br>
3️⃣ Ambil elemen-elemen yang berada di tepi luar dari array `A` dan gabungkan menjadi `Satu array 1D`. <br>
4️⃣ Dapatkan subbarray berikut:
```python
[[20, 40, 60],
 [80, 100, 120],
 [140, 160, 180],
 [200, 220, 240],
 [260, 280, 300]]
```
5️⃣ Dapatkan subbarray berikut:
```python
 [[30, 40],
 [90, 100],
 [150, 160],
 [210, 220]]
```

In [67]:
A = np.array([
    [10, 20, 30, 40, 50, 60],
    [70, 80, 90, 100, 110, 120],
    [130, 140, 150, 160, 170, 180],
    [190, 200, 210, 220, 230, 240],
    [250, 260, 270, 280, 290, 300]
])

elemen = A[3, 1]
print(elemen)

200


In [68]:
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

prime_elements = np.array([[x for x in row if is_prime(x)] for row in A])

print(prime_elements)

[]


In [69]:
top_row = A[0, :]
bottom_row = A[-1, :]
left_col = A[1:-1, 0]
right_col = A[1:-1, -1]

edge_elements = np.concatenate((top_row, bottom_row, left_col, right_col))

print(edge_elements)

[ 10  20  30  40  50  60 250 260 270 280 290 300  70 130 190 120 180 240]


In [70]:
subarray = A[:, [1, 3, 5]]

print(subarray)

[[ 20  40  60]
 [ 80 100 120]
 [140 160 180]
 [200 220 240]
 [260 280 300]]


In [71]:
subarray = A[0:4, 2:4]

print(subarray)

[[ 30  40]
 [ 90 100]
 [150 160]
 [210 220]]


## **📌 Soal 7: Ekspansi Array** 📝

Jika kamu memiliki array ***Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]***, buatlah kode untuk membuat array R berupa: <br>
***R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]***?

In [72]:
Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

R = np.array([Z[i:i+4] for i in range(len(Z) - 3)])

print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
